### ISSUE TITLE
generate PDFium binary ourselves

### ISSUE THREAD

**Issue by juliand665** [mangelio/SimplePDFKit#1]
Currently, we're using a binary from https://github.com/vfr/UXReader-iOS, because we couldn't get PDFium to compile for iOS ourselves. This is bad for multiple reasons: it's bound to break at some point in the future, and it generates a huge binary that probably contains data for some architectures we don't need. Improve this.

**Comment by paulocoutinhox** [comment]
Hello,

Im Paulo from mobile pdfium project on github.

I want your help to make it work with success on iOS. I made all changes to make it build correctly. 

But the final library is not with all symbols and i don't know why. 

Can you help me?

https://github.com/prsolucoes/mobile-pdfium/issues/4

The travis CI is compiling it with success too. Can be a way to check it.

Thanks for any help you can provide :)

Any help will be nice for the community.

**Comment by paulocoutinhox** [comment]
Hi,

The updated binaries is here:
https://github.com/prsolucoes/mobile-pdfium

It works with your sample in simulator and device.

Get prebuilt library on end of file README.md at my repository.

Thanks.

**Comment by juliand665** [comment]
Closing since we've switched to good ol' PDFKit.
